{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "audit-service.fullname" . }}-clickhouse
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "audit-service.fullname" . }}-clickhouse
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.externalSecrets.clickhouse.remoteRef.key }}
        property: nativeUrl
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecrets.clickhouse.remoteRef.key }}
        property: user
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.clickhouse.remoteRef.key }}
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "audit-service.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "audit-service.fullname" . }}-keycloak
    creationPolicy: Owner
  data:
    - secretKey: issuer-uri
      remoteRef:
        key: {{ .Values.externalSecrets.keycloak.remoteRef.key }}
        property: issuer-uri
{{- end }}