{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bff.fullname" . }}-secrets
  labels:
    {{- include "bff.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "bff.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{- range .Values.externalSecrets.secretKeys }}
        {{ .name }}: "{{ `{{ .` }}{{ .key }}{{ ` }}` }}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.vaultPath }}
{{- end }}
