replicaCount: 1

image:
  repository: provectuslabs/kafka-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

kafka:
  name: kafka
  bootstrapServers: kafka-kafka-bootstrap:9092
  username: user
  securityProtocol: SASL_PLAINTEXT
  saslMechanism: SCRAM-SHA-512

openbao:
  enabled: true
  role: "router"
  secretsPath: "kafka"
  resyncInterval: "10s"

ingress:
  enabled: true
  domain: kafka.echo-messenger.ru