apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-infisical
  namespace: tinode
spec:
  resyncInterval: 10

  authentication:
    kubernetesAuth:
      identityId: {{ .Values.infisical.identityId }}
      serviceAccountRef:
        name: {{ .Values.infisical.serviceAccount.name }}
        namespace: {{ .Values.infisical.serviceAccount.namespace }}
      secretsScope:
        envSlug: {{ .Values.infisical.env }}
        projectSlug: {{ .Values.infisical.project }}
        secretsPath: /postgres

  managedKubeSecretReferences:
    - secretName: pg-secret
      secretNamespace: tinode
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          POSTGRES_DB: "{{ .POSTGRES_DB.Value }}"
          POSTGRES_USER: "{{ .POSTGRES_USER.Value }}"
          POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD.Value }}"
