flannel-backend: vxlan

write-kubeconfig-mode: "0600"

kube-apiserver-arg:
  - "profiling=false"
  - "tls-min-version=VersionTLS12"
  - "service-account-lookup=true"

  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"

  - "audit-log-path=/var/log/kubernetes/audit.log"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "audit-policy-file=/etc/rancher/k3s/audit-policy.yaml"

  - "request-timeout=300s"

  - "service-account-issuer=https://kubernetes.default.svc.cluster.local"

  - "encryption-provider-config=/etc/rancher/k3s/encryption-config.yaml"

kube-controller-manager-arg:
  - "profiling=false"
  - "terminated-pod-gc-threshold=10"
  - "use-service-account-credentials=true"

  - "bind-address=127.0.0.1"

kube-scheduler-arg:
  - "profiling=false"

  - "bind-address=127.0.0.1"

kubelet-arg:
  - "rotate-certificates=true"

  - "anonymous-auth=false"

  - "authorization-mode=Webhook"

  - "read-only-port=0"

  - "protect-kernel-defaults=true"

  - "allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding"

  - "event-qps=5"

  - "seccomp-default=true"