apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinode
  namespace: tinode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinode
  template:
    metadata:
      labels:
        app: tinode
    spec:
      containers:
        - name: tinode
          image: tinode/tinode-postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6060
              name: http
          envFrom:
            - secretRef:
                name: pg-secret
          env:
            - name: EXT_CONFIG
              value: /tinode.conf
          volumeMounts:
            - name: tinode-config
              mountPath: /tinode.conf
              subPath: tinode.conf
            - name: uploads
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: tinode-config
          configMap:
            name: tinode-config
            defaultMode: 0755
        - name: uploads
          persistentVolumeClaim:
            claimName: tinode-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tinode
  namespace: tinode
spec:
  type: ClusterIP
  selector:
    app: tinode
  ports:
    - port: 6060
      targetPort: 6060
      name: http
