apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinode-server
  namespace: tinode
  labels:
    app: tinode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinode
  template:
    metadata:
      labels:
        app: tinode
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: tinode
        image: ghcr.io/echomessenger/tinode-server:latest-amd64
        imagePullPolicy: Always
        ports:
          - containerPort: 6060
            name: http
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: POSTGRES_DB
        volumeMounts:
          - name: webapp-data
            mountPath: /webapp
          - name: uploads
            mountPath: /app/uploads
        livenessProbe:
          tcpSocket:
            port: 6060
          initialDelaySeconds: 20
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6060
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: webapp-data
          emptyDir: {}
        - name: uploads
          persistentVolumeClaim:
            claimName: tinode-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tinode
  namespace: tinode
spec:
  type: ClusterIP
  selector:
    app: tinode
  ports:
    - port: 6060
      targetPort: 6060
      name: http
