replicaCount: 1

image:
  tag: "lts-community"

postgresql:
  enabled: true
  auth:
    existingSecret: "sonarqube-postgres-secret"
    database: "sonarqube"
  primary:
    persistence:
      enabled: true
      size: 10Gi

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  hosts:
    - name: sonar.echo-messenger.ru
      path: /
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - sonar.echo-messenger.ru
      secretName: sonar-tls

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

# Важно для Elasticsearch внутри SonarQube
initSysctl:
  enabled: true   # попытается выставить vm.max_map_count, но в k3s лучше делать вручную

jvmOpts: "-Xmx1024m -Xms512m"

monitoringPasscodeSecretName: "sonarqube-monitoring-secret"
monitoringPasscodeSecretKey: "MONITORING_PASSCODE"

community:
  enabled: true

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        wget --no-proxy -qO- --timeout=1 \
          --header="X-Sonar-Passcode: $SONAR_WEB_SYSTEMPASSCODE" \
          http://localhost:9000/api/system/liveness
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  timeoutSeconds: 2

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        wget --no-proxy -qO- http://localhost:9000/api/system/status | grep -q -e '"status":"UP"' -e '"status":"DB_MIGRATION_NEEDED"' -e '"status":"DB_MIGRATION_RUNNING"'
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  timeoutSeconds: 2

startupProbe:
  httpGet:
    path: /api/system/status
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  timeoutSeconds: 2