apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.55.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/charts/infra/monitoring/values-loki.yaml
        parameters:
          - name: deploymentMode
            value: SingleBinary
          - name: loki.schemaConfig.configs[0].from
            value: "2024-01-01"
          - name: loki.schemaConfig.configs[0].store
            value: tsdb
          - name: loki.schemaConfig.configs[0].object_store
            value: filesystem
          - name: loki.schemaConfig.configs[0].schema
            value: v13
          - name: loki.schemaConfig.configs[0].index.prefix
            value: loki_index_
          - name: loki.schemaConfig.configs[0].index.period
            value: 24h
          - name: loki.compactor.retention_enabled
            value: "true"
          - name: loki.compactor.delete_request_store
            value: filesystem

    - repoURL: https://github.com/EchoMessenger/devops.git
      targetRevision: HEAD
      ref: values

  destination:
    namespace: monitoring
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [CreateNamespace=true]