apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    targetRevision: HEAD
    path: charts/infra/monitoring
    directory:
      include: "*.yaml"
      exclude: "values-*.yaml,README.md"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true