# --- KafkaNodePool: controllers (1 шт.)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: local-path
        size: 8Gi
        deleteClaim: true
        kraftMetadata: shared

---
# --- KafkaNodePool: brokers (1 шт.)
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 1
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: local-path
        size: 8Gi
        deleteClaim: true
        kraftMetadata: shared

---
# --- Kafka (KRaft c NodePort + SCRAM)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    # Можно оставить без явных версий, Strimzi подставит совместимые по умолчанию.
    # Если хочешь закрепить:
    # version: 4.1.0
    # metadataVersion: 4.1-IV1
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 30992
          brokers:
            - broker: 0
              nodePort: 30993
          preferredNodePortAddressType: InternalIP
    config:
      # single-node значения репликаций
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
