{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonar.postgresqlName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonar.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      name: postgresql
  selector:
    {{- include "sonar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
