apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.openbao.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets                 # имя K8s Secret
  data:
    - secretKey: admin-password            # для auth.existingSecret
      remoteRef:
        key: {{ .Values.openbao.secrets.keycloak.path }}
        property: admin-password

    - secretKey: postgres-password         # для postgresql superuser
      remoteRef:
        key: {{ .Values.openbao.secrets.keycloak.path }}
        property: postgres-password

    - secretKey: password                  # для postgresql keycloak user
      remoteRef:
        key: {{ .Values.openbao.secrets.keycloak.path }}
        property: password