apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.openbao.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: {{ .Values.openbao.secrets.keycloak.path }}
        property: admin-password

    - secretKey: db-password
      remoteRef:
        key: {{ .Values.openbao.secrets.keycloak.path }}
        property: db-password
