apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}