apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-crd
spec:
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: 15cd709a-c052-440d-9e68-9c4e860ddda9
      serviceAccountRef:
        name: infisical-service-account
        namespace: default
      secretsScope:
        envSlug: dev
        projectSlug: echo-rvq-s
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: kafka-sasl
      secretNamespace: default
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          enable: "{{ .KAFKA_SASL_ENABLE.Value }}"
          mechanism: "{{ .KAFKA_SASL_MECHANISM.Value}}"
          password: "{{ .KAFKA_SASL_PASSWORD.Value}}"
          username: "{{ .KAFKA_SASL_USERNAME.Value}}"
    - secretName: kafka-tls
      secretNamespace: default
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          enable: "{{ .KAFKA_TLS_ENABLE.Value }}"
          insecureSkipVerify: "{{ .KAFKA_TLS_INSECURE_SKIP_VERIFY.Value}}"
    - secretName: postgres
      secretNamespace: tinode
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          db: "{{ .POSTGRES_DB.Value }}"
          password: "{{ .POSTGRES_PASSWORD.Value}}"
          user: "{{ .POSTGRES_USER.Value}}"
    - secretName: tinode
      secretNamespace: tinode
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          apiSalt: "{{ .TINODE_API_KEY_SALT.Value }}"
          frontKey: "{{ .TINODE_FRONT_KEY.Value}}"
          uidKey: "{{ .TINODE_UID_KEY.Value}}"
