image:
  repository: ghcr.io/echomessenger/tinode-router
  tag: latest-amd64
  pullPolicy: Always  # Важно для latest тегов!

replicaCount: 1

service:
  port: 7911
  healthPort: 8090

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "500m"

kafka:
  brokers: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  clientId: router
  topicPrefix: tinode
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    username: "user"
  tls:
    enabled: false
    insecureSkipVerify: false

log:
  level: debug

nodeSelector: {}
affinity: {}
tolerations: []