apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.ctrl
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.data
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 3, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.pres
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 3, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.meta
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.info
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.topic_events
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.account_events
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.subscription_events
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.message_events
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 3, replicas: 1 }
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tinode.dlq
  namespace: kafka
  labels: { strimzi.io/cluster: kafka }
spec: { partitions: 1, replicas: 1 }
