apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-ui-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: kafka-ui-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        sasl_jaas_config: >-
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="{{ .Values.kafka.username }}"
          password="{{ `{{ .password }}` }}";
        AUTH_TYPE: "LOGIN_FORM"
        SPRING_SECURITY_USER_NAME: "admin"
        SPRING_SECURITY_USER_PASSWORD: "{{ `{{ .password }}` }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/{{ .Values.kafka.username }}
        property: password