{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-credentials-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    clickhouse.user: admin
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.clickhouse.defaultUser | quote }}
  CLICKHOUSE_PASSWORD: {{ include "clickhouse.defaultPassword" . | quote }}
  CLICKHOUSE_DB: {{ .Values.clickhouse.defaultDatabase | quote }}
  CLICKHOUSE_HOST: {{ include "clickhouse.fullname" . | quote }}
  CLICKHOUSE_HTTP_PORT: {{ .Values.service.httpPort | quote }}
  CLICKHOUSE_TCP_PORT: {{ .Values.service.tcpPort | quote }}
  CLICKHOUSE_HTTP_URL: "http://{{ include "clickhouse.fullname" . }}:{{ .Values.service.httpPort }}"
  CLICKHOUSE_NATIVE_URL: "clickhouse://{{ .Values.clickhouse.defaultUser }}:{{ include "clickhouse.defaultPassword" . }}@{{ include "clickhouse.fullname" . }}:{{ .Values.service.tcpPort }}/{{ .Values.clickhouse.defaultDatabase }}"
---
{{- range .Values.clickhouse.users }}
{{- $password := .password | default (randAlphaNum 24) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" $ }}-credentials-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
    clickhouse.user: {{ .name }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .name | quote }}
  CLICKHOUSE_PASSWORD: {{ $password | quote }}
  CLICKHOUSE_DB: {{ $.Values.clickhouse.defaultDatabase | quote }}
  CLICKHOUSE_HOST: {{ include "clickhouse.fullname" $ | quote }}
  CLICKHOUSE_HTTP_PORT: {{ $.Values.service.httpPort | quote }}
  CLICKHOUSE_TCP_PORT: {{ $.Values.service.tcpPort | quote }}
  CLICKHOUSE_HTTP_URL: "http://{{ include "clickhouse.fullname" $ }}:{{ $.Values.service.httpPort }}"
  CLICKHOUSE_NATIVE_URL: "clickhouse://{{ .name }}:{{ $password }}@{{ include "clickhouse.fullname" $ }}:{{ $.Values.service.tcpPort }}/{{ $.Values.clickhouse.defaultDatabase }}"
---
{{- end }}
{{- end }}