{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.clickhouse.defaultUser | quote }}
  CLICKHOUSE_PASSWORD: {{ include "clickhouse.defaultPassword" . | quote }}
  CLICKHOUSE_DB: {{ .Values.clickhouse.defaultDatabase | quote }}
  CLICKHOUSE_HTTP_URL: "http://{{ include "clickhouse.fullname" . }}:{{ .Values.service.httpPort }}"
  CLICKHOUSE_NATIVE_URL: {{ include "clickhouse.nativeUrl" . | quote }}
  {{- /* Дополнительные пользователи */}}
  {{- range $index, $user := .Values.clickhouse.users }}
  CLICKHOUSE_USER_{{ $user.name | upper }}_PASSWORD: {{ $user.password | default (randAlphaNum 24) | quote }}
  {{- end }}
{{- end }}