{{- if not .Values.externalSecret.enabled }}
{{- $fullname := include "clickhouse.fullname" . -}}
{{- $adminPassword := include "clickhouse.secretValue" (dict "root" . "secretName" (printf "%s-credentials-admin" $fullname) "secretKey" "CLICKHOUSE_PASSWORD" "value" .Values.clickhouse.defaultPassword "length" 24) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-credentials-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.clickhouse.defaultUser | quote }}
  CLICKHOUSE_PASSWORD: {{ $adminPassword | quote }}
  CLICKHOUSE_HTTP_URL: {{ include "clickhouse.httpUrl" . | quote }}
  CLICKHOUSE_NATIVE_URL: {{ include "clickhouse.nativeUrl" (dict "root" . "username" .Values.clickhouse.defaultUser "password" $adminPassword) | quote }}
  CLICKHOUSE_JDBC_URL: {{ include "clickhouse.jdbcUrl" . | quote }}

{{- range .Values.clickhouse.users }}
{{- $userPassword := include "clickhouse.secretValue" (dict "root" $ "secretName" (printf "%s-credentials-%s" $fullname .name) "secretKey" "CLICKHOUSE_PASSWORD" "value" .password "length" 24) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-credentials-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" $ | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .name | quote }}
  CLICKHOUSE_PASSWORD: {{ $userPassword | quote }}
  CLICKHOUSE_HTTP_URL: {{ include "clickhouse.httpUrl" $ | quote }}
  CLICKHOUSE_NATIVE_URL: {{ include "clickhouse.nativeUrl" (dict "root" $ "username" .name "password" $userPassword) | quote }}
  CLICKHOUSE_JDBC_URL: {{ include "clickhouse.jdbcUrl" $ | quote }}
{{- end }}
{{- end }}
