apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingestor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    path: charts/apps/ingestor
    targetRevision: HEAD
    helm:
      releaseName: ingestor
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestor
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [CreateNamespace=true]
