apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tinode
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    path: charts/apps/tinode
    targetRevision: HEAD
    helm:
      releaseName: tinode
      valueFiles:
        - values.yaml
        - values-performance.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tinode
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [CreateNamespace=true]
