---
# Kafka user password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-user
  namespace: kafka
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: password
    remoteRef:
      key: secret/kafka/user
      property: password

---
# Kafka SASL config
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-sasl
  namespace: kafka
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-sasl
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ENABLE
    remoteRef:
      key: secret/kafka/sasl
      property: ENABLE
  - secretKey: MECHANISM
    remoteRef:
      key: secret/kafka/sasl
      property: MECHANISM

---
# Kafka TLS config
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-tls
  namespace: kafka
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-tls
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ENABLE
    remoteRef:
      key: secret/kafka/tls
      property: ENABLE
  - secretKey: INSECURE_SKIP_VERIFY
    remoteRef:
      key: secret/kafka/tls
      property: INSECURE_SKIP_VERIFY