apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
  access-key: {{ .Values.minio.rootUser | quote }}
  secret-key: {{ .Values.minio.rootPassword | quote }}
  endpoint: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "minio.fullname" .) .Release.Namespace .Values.service.apiPort | quote }}
  region: {{ .Values.minio.region | quote }}
  bucket: {{ .Values.minio.bucket.name | quote }}
