{{- if .Values.openbao.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.openbao.secretsPath }}/user
      property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-sasl
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-sasl
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ENABLE
    remoteRef:
      key: {{ .Values.openbao.secretsPath }}/sasl
      property: ENABLE
  - secretKey: MECHANISM
    remoteRef:
      key: {{ .Values.openbao.secretsPath }}/sasl
      property: MECHANISM

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-tls
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: kafka-tls
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ENABLE
    remoteRef:
      key: {{ .Values.openbao.secretsPath }}/tls
      property: ENABLE
  - secretKey: INSECURE_SKIP_VERIFY
    remoteRef:
      key: {{ .Values.openbao.secretsPath }}/tls
      property: INSECURE_SKIP_VERIFY
{{- end }}