{{- if .Values.openbao.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.server }}
      path: {{ .Values.openbao.path }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.openbao.role }}
          serviceAccountRef:
            name: {{ .Values.openbao.serviceAccount }}
      {{- if .Values.openbao.caBundle }}
      caBundle: {{ .Values.openbao.caBundle | quote }}
      {{- end }}
{{- end }}