apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    path: charts/infra/kafka
    targetRevision: HEAD
    helm:
      releaseName: kafka
      valueFiles:
        - values.yaml
        - values-performance.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [CreateNamespace=true]
