apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tinode
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    path: charts/infra/minio-tinode
    targetRevision: HEAD
    helm:
      releaseName: minio-tinode
  destination:
    server: https://kubernetes.default.svc
    namespace: tinode
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: minio-tinode-bucket-init
      jsonPointers:
        - /spec/template/spec/containers/0/image