apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasktracker-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/EchoMessenger/devops.git
    path: charts/infra/tasktracker-postgres
    targetRevision: HEAD
    helm:
      releaseName: tasktracker-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: tasktracker
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]