{{- if .Values.webrtc.iceServersSecret.create }}
{{- $iceServersSecretName := .Values.webrtc.iceServersSecret.name -}}
{{- if not $iceServersSecretName -}}
{{- $iceServersSecretName = printf "%s-webrtc" (include "tinode.fullname" .) -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $iceServersSecretName | quote }}
  labels:
    {{- include "tinode.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webrtc.iceServersSecret.key }}: |
    {{- .Values.webrtc.iceServersSecret.iceServers | toPrettyJson | nindent 4 }}
{{- end }}
